"""fix: change login max str size to 256 (user table)

Revision ID: 20f2211bf80e
Revises: 065b4bc1fa5b
Create Date: 2025-06-21 11:54:35.070645

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20f2211bf80e'
down_revision: str | Sequence[str] | None = '065b4bc1fa5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
